version: '3'
services:
  db:
    image: mysql:5.7
    env_file: docker.env
    volumes:
    # Here weâ€™re telling the db container to look in that data folder for a .sql export 
    # and to use it to populate our database.
      - ./data:/docker-entrypoint-initdb.d
    restart: always # always restart the container after reboot
    ports:
      - "3306:3306"

  wordpress: # name of our wordpress container
    depends_on: # container dependencies that need to be running first
      - db
    image: wordpress:latest # image used by our container
    ports:
      - "1973:80" # setting our ports for networking
    restart: always
    env_file: docker.env
    volumes: # this is where we tell Docker what to pay attention to
      - ./wp-content:/var/www/html/wp-content # mapping our custom theme to the container

  myadmin:
    env_file: docker.env
    image: phpmyadmin/phpmyadmin:4.8.1
    ports:
      - "8080:80"
    restart: always
    links:
      - db
    depends_on:
      - db
